name: CD

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ~1.19.1

      - name: Build
        run: |
          go get -d -v
          go build -v .

      - name: Run tests
        run: go test -v ./...